/**
 * build-brief.js — Phase 6: Homepage Brief
 *
 * Reads:   data/heat-map.json, data/personas.json
 * Writes:  data/homepage-brief.js
 *
 * Derives the homepage routing strategy from heat scores:
 *   - Above-the-fold: highest-heat pages, must be reachable in 1 click
 *   - Primary CTA: HR buyer conversion action (highest-priority persona)
 *   - Secondary CTAs: broker conversion + next-tier high-heat pages
 *   - Excluded: low-heat pages that don't earn homepage real estate
 *
 * Usage: node src/build-brief.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

function load(file) {
  const p = path.join(ROOT, 'data', file);
  if (!fs.existsSync(p)) { console.error(`Missing: ${p}`); process.exit(1); }
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function save(filename, varName, data) {
  const out = `// Auto-generated by src/build-brief.js — ${new Date().toISOString()}\nwindow.${varName} = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(path.join(ROOT, 'data', filename), out);
  console.log(`Wrote data/${filename}`);
}

function main() {
  const heatMap  = load('heat-map.json');
  const personas = load('personas.json');

  if (!heatMap.pages || heatMap.pages.length === 0) {
    console.log('Heat map is empty. Run npm run score first.');
    process.exit(0);
  }

  const highPages   = heatMap.pages.filter(p => p.heatLevel === 'high');
  const medPages    = heatMap.pages.filter(p => p.heatLevel === 'medium');
  const lowPages    = heatMap.pages.filter(p => p.heatLevel === 'low');

  const hrPersona     = personas.personas.find(p => p.id === 'hr-benefits-manager');
  const brokerPersona = personas.personas.find(p => p.id === 'benefits-consultant');

  // Above the fold: top high-heat pages (ideally 1 click from homepage)
  const aboveTheFold = highPages.slice(0, 5).map(p => ({
    pageId: p.id,
    pageName: p.name,
    url: p.url,
    heatScore: p.heatScore,
    personasServed: p.personasServed,
    rationale: `Heat score ${p.heatScore} — serves ${p.personasServed.join(' + ')}`
  }));

  // Primary CTA: HR buyer conversion (demo request)
  const primaryCTA = {
    personaId: 'hr-benefits-manager',
    action: hrPersona.conversionAction,
    rationale: 'Primary buyer persona. Demo request is the highest-value conversion for sales pipeline.',
    placement: 'Above the fold, primary button, repeated in nav'
  };

  // Secondary CTAs: broker conversion + not-yet-ready HR buyers
  const secondaryCTAs = [
    {
      personaId: 'benefits-consultant',
      action: brokerPersona.conversionAction,
      rationale: 'Broker persona needs a distinct path — they are not booking demos, they need materials.',
      placement: 'Secondary CTA area or dedicated broker pathway'
    },
    {
      personaId: 'hr-benefits-manager',
      action: 'Explore resources / case studies',
      rationale: 'Visitors not yet ready to demo need a trust-building next step.',
      placement: 'Below primary CTA or as tertiary nav link'
    }
  ];

  // Routing strategy: which persona gets which path from homepage
  const routingStrategy = {
    splitPoint: 'Above the fold — messaging and CTAs should self-select each persona',
    hrBuyerPath: {
      label: 'HR / Benefits Leader path',
      headline: 'Speak to ROI, utilization, compliance',
      primaryCTA: hrPersona.conversionAction,
      highestHeatPages: highPages.filter(p => p.personasServed.includes('hr-benefits-manager')).slice(0, 3).map(p => p.name)
    },
    brokerPath: {
      label: 'Broker path',
      headline: 'Speak to differentiation, implementation, broker support',
      primaryCTA: brokerPersona.conversionAction,
      highestHeatPages: highPages.filter(p => p.personasServed.includes('benefits-consultant')).slice(0, 3).map(p => p.name)
    }
  };

  // What doesn't earn homepage real estate
  const excludedFromHomepage = lowPages.map(p => ({
    pageId: p.id,
    pageName: p.name,
    heatScore: p.heatScore,
    reason: 'Low heat score — does not serve a priority user story for either persona'
  }));

  const output = {
    status: 'generated',
    generated: new Date().toISOString(),
    corePrinciple: 'The homepage is not a brand statement. It is a routing layer.',
    aboveTheFold,
    primaryCTA,
    secondaryCTAs,
    routingStrategy,
    excludedFromHomepage,
    contentGaps: heatMap.summary.gaps
  };

  save('homepage-brief.js', 'HOMEPAGE_BRIEF', output);
  fs.writeFileSync(path.join(ROOT, 'data', 'homepage-brief.json'), JSON.stringify(output, null, 2));
  console.log('Wrote data/homepage-brief.json');
  console.log(`Above fold: ${aboveTheFold.length} pages | Excluded: ${excludedFromHomepage.length} pages`);
  console.log('Done. Open homepage-brief.html to review.');
}

main();
