/**
 * map-flows.js — Phase 4: Flow Mapping
 *
 * Reads:   data/sitemap.json, data/user-stories.json, data/personas.json
 * Writes:  data/flows.js
 *
 * For each user story, this script traces the expected path through the sitemap:
 *   entry point → homepage → intermediate pages → conversion page
 *
 * Usage: node src/map-flows.js
 *
 * NOTE: After running, open flows.html to review the diagrams.
 * Manual path assignment is expected — this script scaffolds the structure.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

function load(file) {
  const p = path.join(ROOT, 'data', file);
  if (!fs.existsSync(p)) { console.error(`Missing: ${p}`); process.exit(1); }
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function save(filename, varName, data) {
  const out = `// Auto-generated by src/map-flows.js — ${new Date().toISOString()}\nwindow.${varName} = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(path.join(ROOT, 'data', filename), out);
  console.log(`Wrote data/${filename}`);
}

function main() {
  const sitemap = load('sitemap.json');
  const stories = load('user-stories.json');
  const personas = load('personas.json');

  if (!sitemap.pages || sitemap.pages.length === 0) {
    console.log('Sitemap is empty — nothing to map. Add pages to data/sitemap.json first.');
    process.exit(0);
  }

  const pageById = Object.fromEntries(sitemap.pages.map(p => [p.id, p]));

  // Build per-persona flow groups
  const flows = personas.personas.map(persona => {
    const personaStories = stories.userStories.filter(s => s.personaId === persona.id);

    const paths = personaStories.map(story => {
      // Each story maps to a path: entry → pages → conversion
      // pageIds are assigned manually (or via future enrichment)
      const resolvedPages = (story.pageIds || []).map(pid => {
        const pg = pageById[pid];
        return pg ? { id: pg.id, name: pg.name, url: pg.url } : { id: pid, name: pid, url: '' };
      });

      const clickDepth = resolvedPages.length > 0 ? resolvedPages.length - 1 : null;

      return {
        storyId: story.id,
        jobToBeDone: story.jobToBeDone,
        entryChannel: story.entryChannel,
        priority: story.priority,
        successMetric: story.successMetric,
        path: resolvedPages,
        clickDepth,
        conversionPage: resolvedPages[resolvedPages.length - 1] || null
      };
    });

    return {
      personaId: persona.id,
      personaName: persona.name,
      conversionAction: persona.conversionAction,
      paths
    };
  });

  const output = {
    status: 'generated',
    generated: new Date().toISOString(),
    flows
  };

  save('flows.js', 'FLOWS', output);

  // Also save JSON for reference
  fs.writeFileSync(path.join(ROOT, 'data', 'flows.json'), JSON.stringify(output, null, 2));
  console.log('Wrote data/flows.json');
  console.log('Done. Review flows.html to validate paths.');
}

main();
