/**
 * score-heatmap.js — Phase 5: Heat Map & Gap Analysis
 *
 * Reads:   data/sitemap.json, data/user-stories.json, data/flows.json
 * Writes:  data/heat-map.js
 *
 * Composite heat score per page from 5 signals (per strategy doc):
 *   1. storyCoverage     — how many user stories from how many personas route through this page
 *   2. conversionProximity — how many clicks from this page to a primary conversion action
 *   3. entryFrequency    — likelihood of this page being a first-impression landing point
 *   4. dropOffRisk       — how likely a persona is to abandon if this page underdelivers
 *   5. audienceOverlap   — whether this page must serve multiple personas simultaneously
 *
 * Scores are 0–10 per signal. Composite = weighted average.
 * Heat level: high (7+), medium (4–6.9), low (<4)
 *
 * Usage: node src/score-heatmap.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const WEIGHTS = {
  storyCoverage:       0.30,
  conversionProximity: 0.25,
  entryFrequency:      0.20,
  dropOffRisk:         0.15,
  audienceOverlap:     0.10
};

function load(file) {
  const p = path.join(ROOT, 'data', file);
  if (!fs.existsSync(p)) { console.error(`Missing: ${p}`); process.exit(1); }
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function save(filename, varName, data) {
  const out = `// Auto-generated by src/score-heatmap.js — ${new Date().toISOString()}\nwindow.${varName} = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(path.join(ROOT, 'data', filename), out);
  console.log(`Wrote data/${filename}`);
}

function heatLevel(score) {
  if (score >= 7) return 'high';
  if (score >= 4) return 'medium';
  return 'low';
}

function main() {
  const sitemap = load('sitemap.json');
  const stories = load('user-stories.json');
  const flows   = load('flows.json');

  if (!sitemap.pages || sitemap.pages.length === 0) {
    console.log('Sitemap is empty. Add pages to data/sitemap.json first.');
    process.exit(0);
  }

  // Build lookup: pageId → list of stories that route through it
  const pageStories = {};  // pageId → [{ storyId, personaId, priority }]
  for (const flow of flows.flows) {
    for (const p of flow.paths) {
      for (const page of p.path) {
        if (!pageStories[page.id]) pageStories[page.id] = [];
        pageStories[page.id].push({ storyId: p.storyId, personaId: flow.personaId, priority: p.priority });
      }
    }
  }

  // Identify conversion pages (last page in each path)
  const conversionPageIds = new Set();
  for (const flow of flows.flows) {
    for (const p of flow.paths) {
      if (p.conversionPage) conversionPageIds.add(p.conversionPage.id);
    }
  }

  // Identify homepage
  const homepage = sitemap.pages.find(p => p.navTier === 0 || p.id === 'home' || p.url === '/');
  const homepageId = homepage ? homepage.id : null;

  // Score each page — skip nav structural items (dropdowns and CTAs are not content pages)
  const scoredPages = sitemap.pages.filter(p => p.type !== 'nav-dropdown' && p.type !== 'nav-cta' && p.type !== 'footer-cta').map(page => {
    const linked = pageStories[page.id] || [];
    const personasReached = new Set(linked.map(s => s.personaId));

    // 1. Story coverage: (unique stories * priority weight) / max possible, scaled 0–10
    const coverageRaw = linked.reduce((sum, s) => sum + (5 - s.priority), 0); // priority 1 = 4pts, 4 = 1pt
    const storyCoverage = Math.min(10, coverageRaw * 1.5);

    // 2. Conversion proximity: 10 if conversion page, decreases by 2 per click
    //    We use the shortest path in flows to estimate clicks to conversion
    let minClicksToConversion = 99;
    for (const flow of flows.flows) {
      for (const p of flow.paths) {
        const pageIdx = p.path.findIndex(pg => pg.id === page.id);
        if (pageIdx >= 0 && p.conversionPage) {
          const convIdx = p.path.findIndex(pg => pg.id === p.conversionPage.id);
          if (convIdx >= pageIdx) {
            minClicksToConversion = Math.min(minClicksToConversion, convIdx - pageIdx);
          }
        }
      }
    }
    const conversionProximity = minClicksToConversion === 99 ? 0 : Math.max(0, 10 - minClicksToConversion * 2);

    // 3. Entry frequency: 10 for homepage, 8 for navTier 1 pages, 5 for tier 2, etc.
    const tierScores = { 0: 10, 1: 7, 2: 4, 3: 2 };
    const entryFrequency = tierScores[page.navTier] || 1;

    // 4. Drop-off risk — three independent signals:
    //    a) Bottleneck: how many distinct P1 paths depend on this page (more = higher stakes)
    //    b) Funnel depth: pages in the middle of a flow have highest abandonment risk
    //       (parabola: 0 at entry and conversion ends, peaks at midpoint)
    //    c) Known gap: any P1 story routing here already has a content gap note

    // Collect all P1 flow paths that include this page
    const p1Paths = [];
    for (const flow of flows.flows) {
      for (const p of flow.paths) {
        if (p.priority !== 1) continue;
        const idx = p.path.findIndex(pg => pg.id === page.id);
        if (idx >= 0) p1Paths.push({ pathLen: p.path.length, pageIdx: idx });
      }
    }

    // a) Bottleneck: 2 P1 paths → 4pts, 5+ P1 paths → 10pts
    const bottleneckScore = Math.min(10, p1Paths.length * 2);

    // b) Funnel depth: parabola 4·r·(1−r) — 0 at r=0 (entry) and r=1 (conversion), 1 at r=0.5
    let depthScore = 0;
    if (p1Paths.length > 0) {
      const avgRisk = p1Paths.reduce((sum, { pathLen, pageIdx }) => {
        if (pathLen <= 1) return sum;
        const r = pageIdx / (pathLen - 1);
        return sum + 4 * r * (1 - r);
      }, 0) / p1Paths.length;
      depthScore = Math.round(avgRisk * 10);
    }

    // c) Known gap: any P1 story routing through this page has a contentGapNote
    const hasKnownGap = linked.some(l => {
      if (l.priority !== 1) return false;
      const story = (stories.userStories || []).find(s => s.id === l.storyId);
      return story && story.contentGapNote;
    });
    const gapScore = hasKnownGap ? 10 : 0;

    // Weighted composite: bottleneck + depth weighted equally, gap acts as a flag
    const dropOffRisk = Math.min(10, Math.round(
      (bottleneckScore * 0.4 + depthScore * 0.4 + gapScore * 0.2) * 10
    ) / 10);

    // 5. Audience overlap: 10 if serves both personas, 5 if serves one, 0 if none
    const audienceOverlap = personasReached.size >= 2 ? 10 : personasReached.size === 1 ? 5 : 0;

    // Composite weighted score
    const composite = (
      storyCoverage       * WEIGHTS.storyCoverage +
      conversionProximity * WEIGHTS.conversionProximity +
      entryFrequency      * WEIGHTS.entryFrequency +
      dropOffRisk         * WEIGHTS.dropOffRisk +
      audienceOverlap     * WEIGHTS.audienceOverlap
    );
    const score = Math.round(composite * 10) / 10;

    // Content gap detection
    const contentGaps = [];
    if (personasReached.has('hr-buyer') && !linked.some(s => s.personaId === 'hr-buyer' && s.priority === 1)) {
      contentGaps.push('HR buyer has no priority-1 story routed here — verify content relevance');
    }
    if (heatLevel(score) === 'high' && page.navTier > 2) {
      contentGaps.push('High-heat page is 3+ levels deep in the nav — consider elevating or adding a cross-link from a tier-2 page');
    }

    return {
      id: page.id,
      name: page.name,
      url: page.url,
      navTier: page.navTier,
      heatScore: score,
      heatLevel: heatLevel(score),
      personasServed: Array.from(personasReached),
      storiesRouted: linked.length,
      signals: {
        storyCoverage:       Math.round(storyCoverage * 10) / 10,
        conversionProximity: Math.round(conversionProximity * 10) / 10,
        entryFrequency:      Math.round(entryFrequency * 10) / 10,
        dropOffRisk:         Math.round(dropOffRisk * 10) / 10,
        audienceOverlap:     Math.round(audienceOverlap * 10) / 10
      },
      contentGaps
    };
  });

  // Sort by heat score descending
  scoredPages.sort((a, b) => b.heatScore - a.heatScore);

  const allGaps = scoredPages.flatMap(p => p.contentGaps.map(g => ({ page: p.name, gap: g })));
  const summary = {
    high:   scoredPages.filter(p => p.heatLevel === 'high').length,
    medium: scoredPages.filter(p => p.heatLevel === 'medium').length,
    low:    scoredPages.filter(p => p.heatLevel === 'low').length,
    gaps:   allGaps
  };

  const output = {
    status: 'generated',
    generated: new Date().toISOString(),
    weights: WEIGHTS,
    summary,
    pages: scoredPages
  };

  save('heat-map.js', 'HEAT_MAP', output);
  fs.writeFileSync(path.join(ROOT, 'data', 'heat-map.json'), JSON.stringify(output, null, 2));
  console.log('Wrote data/heat-map.json');
  console.log(`Summary: ${summary.high} high, ${summary.medium} medium, ${summary.low} low | ${allGaps.length} gaps`);
  console.log('Done. Open index.html to review heat map.');
}

main();
